version: "3"

networks:
  whaticket:

services:
  chrome:
    image: browserless/chrome:latest
    environment:
      - MAX_CONCURRENT_SESSIONS=${MAX_CONCURRENT_SESSIONS:-1}
    networks:
      - whaticket

  backend:
    environment:
      - CHROME_WS=ws://chrome:3000
